### ISSUE TITLE
Correct number/license plates

### ISSUE THREAD

**Issue by LarsRaschke** [LarsRaschke/CobraCar#5]
function to check the correctness of license plates

**Comment by LarsRaschke** [comment]
own class or only function?
    public boolean test(String licensePlate){
        return (Pattern.matches("[A-Z][A-Z]?[A-Z]?\\-[A-Z][A-Z]*[0-9][0-9]*", licensePlate));
    }
Example : "F-FL2320"

**Comment by ankewithake** [comment]
Added test for increaseMileage as an example of test cases. You will find it in a new folder named src/test model VehicleTest.

**Comment by ankewithake** [comment]
or do you mean a function that checks the licensePlate on right format while creating a new vehicle?
then i would write a method in FleetManager named checkLicensePlate or checkFormat.

**Comment by LarsRaschke** [comment]
checking the right format
